/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAstScorerRouteImport } from './routes/api/ast-scorer'

const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstScorerRoute = ApiAstScorerRouteImport.update({
  id: '/api/ast-scorer',
  path: '/api/ast-scorer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/api/ast-scorer': typeof ApiAstScorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/api/ast-scorer': typeof ApiAstScorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/api/ast-scorer': typeof ApiAstScorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/resume-builder' | '/api/ast-scorer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resume-builder' | '/api/ast-scorer'
  id: '__root__' | '/' | '/resume-builder' | '/api/ast-scorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  ApiAstScorerRoute: typeof ApiAstScorerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ast-scorer': {
      id: '/api/ast-scorer'
      path: '/api/ast-scorer'
      fullPath: '/api/ast-scorer'
      preLoaderRoute: typeof ApiAstScorerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  ApiAstScorerRoute: ApiAstScorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
