/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMockErrorRouteImport } from './routes/api/mock-error'
import { Route as ApiCvImprovRouteImport } from './routes/api/cv-improv'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockErrorRoute = ApiMockErrorRouteImport.update({
  id: '/api/mock-error',
  path: '/api/mock-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvImprovRoute = ApiCvImprovRouteImport.update({
  id: '/api/cv-improv',
  path: '/api/cv-improv',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cv-improv': typeof ApiCvImprovRoute
  '/api/mock-error': typeof ApiMockErrorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cv-improv': typeof ApiCvImprovRoute
  '/api/mock-error': typeof ApiMockErrorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cv-improv': typeof ApiCvImprovRoute
  '/api/mock-error': typeof ApiMockErrorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cv-improv' | '/api/mock-error'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cv-improv' | '/api/mock-error'
  id: '__root__' | '/' | '/api/cv-improv' | '/api/mock-error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCvImprovRoute: typeof ApiCvImprovRoute
  ApiMockErrorRoute: typeof ApiMockErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock-error': {
      id: '/api/mock-error'
      path: '/api/mock-error'
      fullPath: '/api/mock-error'
      preLoaderRoute: typeof ApiMockErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv-improv': {
      id: '/api/cv-improv'
      path: '/api/cv-improv'
      fullPath: '/api/cv-improv'
      preLoaderRoute: typeof ApiCvImprovRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCvImprovRoute: ApiCvImprovRoute,
  ApiMockErrorRoute: ApiMockErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
